# Generated by Django 2.0.5 on 2018-09-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180830_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.BigIntegerField()),
                ('picture_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
