# Generated by Django 2.1 on 2018-09-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_wish_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish_list',
            name='wish_listings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
