# Generated by Django 2.0.5 on 2018-10-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20181002_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nonmembookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('listing_id', models.BigIntegerField()),
                ('visitor_name', models.TextField(blank=True, null=True)),
                ('visitor_phone', models.TextField(blank=True, null=True)),
                ('visitor_email', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cancellation', models.BooleanField(default=False)),
            ],
        ),
    ]
