# Generated by Django 2.0.5 on 2018-10-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_nonmembookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonmembookings',
            name='cancellation',
        ),
        migrations.AddField(
            model_name='nonmembookings',
            name='booking_reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
